spring:
  application:
    name: mcp-server-sse-spring

  api:
    enabled: true
    stdio: false
    version: 1.0
    name: mcp-server-sse-spring
    sse-endpoint: /sse
    sse-messages-endpoint: /sse/messages
    type: sync
    capabilities:
      tool: true
      completing: false
      prompt: false
      resource: false

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE