server:
  port: 8080
  shutdown: immediate

spring:
  application:
    name: mcp-server-sse-spring

  ai:
    mcp:
      server:
        version: 1.0
        name: mcp-server-sse-spring
        sse-endpoint: /sse
        sse-message-endpoint: /sse/messages
        type: sync
        capabilities:
          tool: true
          completion: true
          prompt: true
          resource: true
        keep-alive-interval: 30s

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
